# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from user_post import user_post_pb2 as user__post_dot_user__post__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in user_post/user_post_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class UserPostStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetByUsername = channel.unary_unary(
            "/user_post.UserPost/GetByUsername",
            request_serializer=user__post_dot_user__post__pb2.GetByUsernameRequest.SerializeToString,
            response_deserializer=user__post_dot_user__post__pb2.UserId.FromString,
            _registered_method=True,
        )
        self.GetByID = channel.unary_unary(
            "/user_post.UserPost/GetByID",
            request_serializer=user__post_dot_user__post__pb2.GetByIdRequest.SerializeToString,
            response_deserializer=user__post_dot_user__post__pb2.UserUsername.FromString,
            _registered_method=True,
        )
        self.GetByIDs = channel.unary_unary(
            "/user_post.UserPost/GetByIDs",
            request_serializer=user__post_dot_user__post__pb2.GetByIdsRequest.SerializeToString,
            response_deserializer=user__post_dot_user__post__pb2.UsersMapResponse.FromString,
            _registered_method=True,
        )


class UserPostServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetByUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetByIDs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_UserPostServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetByUsername": grpc.unary_unary_rpc_method_handler(
            servicer.GetByUsername,
            request_deserializer=user__post_dot_user__post__pb2.GetByUsernameRequest.FromString,
            response_serializer=user__post_dot_user__post__pb2.UserId.SerializeToString,
        ),
        "GetByID": grpc.unary_unary_rpc_method_handler(
            servicer.GetByID,
            request_deserializer=user__post_dot_user__post__pb2.GetByIdRequest.FromString,
            response_serializer=user__post_dot_user__post__pb2.UserUsername.SerializeToString,
        ),
        "GetByIDs": grpc.unary_unary_rpc_method_handler(
            servicer.GetByIDs,
            request_deserializer=user__post_dot_user__post__pb2.GetByIdsRequest.FromString,
            response_serializer=user__post_dot_user__post__pb2.UsersMapResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "user_post.UserPost", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("user_post.UserPost", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class UserPost(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetByUsername(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/user_post.UserPost/GetByUsername",
            user__post_dot_user__post__pb2.GetByUsernameRequest.SerializeToString,
            user__post_dot_user__post__pb2.UserId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetByID(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/user_post.UserPost/GetByID",
            user__post_dot_user__post__pb2.GetByIdRequest.SerializeToString,
            user__post_dot_user__post__pb2.UserUsername.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetByIDs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/user_post.UserPost/GetByIDs",
            user__post_dot_user__post__pb2.GetByIdsRequest.SerializeToString,
            user__post_dot_user__post__pb2.UsersMapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
