# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from post import post_pb2 as post_dot_post__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in post/post_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PostStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePost = channel.unary_unary(
                '/post.Post/CreatePost',
                request_serializer=post_dot_post__pb2.PostCreateRequest.SerializeToString,
                response_deserializer=post_dot_post__pb2.PostOutResponse.FromString,
                _registered_method=True)
        self.DeletePost = channel.unary_unary(
                '/post.Post/DeletePost',
                request_serializer=post_dot_post__pb2.PostDeleteRequest.SerializeToString,
                response_deserializer=post_dot_post__pb2.Empty.FromString,
                _registered_method=True)
        self.GetGroupPost = channel.unary_unary(
                '/post.Post/GetGroupPost',
                request_serializer=post_dot_post__pb2.PostGetGroupRequest.SerializeToString,
                response_deserializer=post_dot_post__pb2.PostListResponse.FromString,
                _registered_method=True)
        self.GetByIdPost = channel.unary_unary(
                '/post.Post/GetByIdPost',
                request_serializer=post_dot_post__pb2.PostGetByIdRequest.SerializeToString,
                response_deserializer=post_dot_post__pb2.PostOutResponse.FromString,
                _registered_method=True)
        self.GetByIdUserPost = channel.unary_unary(
                '/post.Post/GetByIdUserPost',
                request_serializer=post_dot_post__pb2.PostGetByIdUserRequest.SerializeToString,
                response_deserializer=post_dot_post__pb2.PostListResponse.FromString,
                _registered_method=True)
        self.PutPost = channel.unary_unary(
                '/post.Post/PutPost',
                request_serializer=post_dot_post__pb2.PostPutRequest.SerializeToString,
                response_deserializer=post_dot_post__pb2.PostOutResponse.FromString,
                _registered_method=True)


class PostServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetByIdPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetByIdUserPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=post_dot_post__pb2.PostCreateRequest.FromString,
                    response_serializer=post_dot_post__pb2.PostOutResponse.SerializeToString,
            ),
            'DeletePost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePost,
                    request_deserializer=post_dot_post__pb2.PostDeleteRequest.FromString,
                    response_serializer=post_dot_post__pb2.Empty.SerializeToString,
            ),
            'GetGroupPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupPost,
                    request_deserializer=post_dot_post__pb2.PostGetGroupRequest.FromString,
                    response_serializer=post_dot_post__pb2.PostListResponse.SerializeToString,
            ),
            'GetByIdPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByIdPost,
                    request_deserializer=post_dot_post__pb2.PostGetByIdRequest.FromString,
                    response_serializer=post_dot_post__pb2.PostOutResponse.SerializeToString,
            ),
            'GetByIdUserPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByIdUserPost,
                    request_deserializer=post_dot_post__pb2.PostGetByIdUserRequest.FromString,
                    response_serializer=post_dot_post__pb2.PostListResponse.SerializeToString,
            ),
            'PutPost': grpc.unary_unary_rpc_method_handler(
                    servicer.PutPost,
                    request_deserializer=post_dot_post__pb2.PostPutRequest.FromString,
                    response_serializer=post_dot_post__pb2.PostOutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'post.Post', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('post.Post', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Post(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/post.Post/CreatePost',
            post_dot_post__pb2.PostCreateRequest.SerializeToString,
            post_dot_post__pb2.PostOutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/post.Post/DeletePost',
            post_dot_post__pb2.PostDeleteRequest.SerializeToString,
            post_dot_post__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/post.Post/GetGroupPost',
            post_dot_post__pb2.PostGetGroupRequest.SerializeToString,
            post_dot_post__pb2.PostListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetByIdPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/post.Post/GetByIdPost',
            post_dot_post__pb2.PostGetByIdRequest.SerializeToString,
            post_dot_post__pb2.PostOutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetByIdUserPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/post.Post/GetByIdUserPost',
            post_dot_post__pb2.PostGetByIdUserRequest.SerializeToString,
            post_dot_post__pb2.PostListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/post.Post/PutPost',
            post_dot_post__pb2.PostPutRequest.SerializeToString,
            post_dot_post__pb2.PostOutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
