# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: admin/admin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'admin/admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x64min/admin.proto\x12\x05\x61\x64min\"$\n\x11\x44\x65letePostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\"$\n\x11\x44\x65leteUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"!\n\x0e\x42\x61nUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\xa3\x01\n\x05\x41\x64min\x12\x34\n\nDeletePost\x12\x18.admin.DeletePostRequest\x1a\x0c.admin.Empty\x12\x34\n\nDeleteUser\x12\x18.admin.DeleteUserRequest\x1a\x0c.admin.Empty\x12.\n\x07\x42\x61nUser\x12\x15.admin.BanUserRequest\x1a\x0c.admin.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin.admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DELETEPOSTREQUEST']._serialized_start=28
  _globals['_DELETEPOSTREQUEST']._serialized_end=64
  _globals['_DELETEUSERREQUEST']._serialized_start=66
  _globals['_DELETEUSERREQUEST']._serialized_end=102
  _globals['_BANUSERREQUEST']._serialized_start=104
  _globals['_BANUSERREQUEST']._serialized_end=137
  _globals['_EMPTY']._serialized_start=139
  _globals['_EMPTY']._serialized_end=146
  _globals['_ADMIN']._serialized_start=149
  _globals['_ADMIN']._serialized_end=312
# @@protoc_insertion_point(module_scope)
