# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "user/user.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fuser/user.proto\x12\x04user"\x1f\n\x11UserDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05"\x1c\n\x0eUserGetRequest\x12\n\n\x02id\x18\x01 \x01(\x05"1\n\x11UserUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t"#\n\x0fUserOutResponse\x12\x10\n\x08username\x18\x01 \x01(\t"\x07\n\x05\x45mpty2\xb0\x01\n\x04User\x12\x32\n\nDeleteUser\x12\x17.user.UserDeleteRequest\x1a\x0b.user.Empty\x12\x36\n\x07GetUser\x12\x14.user.UserGetRequest\x1a\x15.user.UserOutResponse\x12<\n\nUserUpdate\x12\x17.user.UserUpdateRequest\x1a\x15.user.UserOutResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "user.user_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_USERDELETEREQUEST"]._serialized_start = 25
    _globals["_USERDELETEREQUEST"]._serialized_end = 56
    _globals["_USERGETREQUEST"]._serialized_start = 58
    _globals["_USERGETREQUEST"]._serialized_end = 86
    _globals["_USERUPDATEREQUEST"]._serialized_start = 88
    _globals["_USERUPDATEREQUEST"]._serialized_end = 137
    _globals["_USEROUTRESPONSE"]._serialized_start = 139
    _globals["_USEROUTRESPONSE"]._serialized_end = 174
    _globals["_EMPTY"]._serialized_start = 176
    _globals["_EMPTY"]._serialized_end = 183
    _globals["_USER"]._serialized_start = 186
    _globals["_USER"]._serialized_end = 362
# @@protoc_insertion_point(module_scope)
